// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBot;

namespace TelegramBot_2020_Righi_Montanari_NetCore.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20200114170012_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("TelegramBot.Professore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Flag_Ban")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flag_Circolari")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flag_Condizioni")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flag_Feedback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Professori");
                });

            modelBuilder.Entity("TelegramBot.Studente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Flag_Ban")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flag_Circolari")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flag_Feedback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
